import { createElement as h } from 'react'
import { rotaryKilnData } from '../data/rotaryKilnData.js'
import { ROTARY_KILN_MODEL_URL } from '../scene/rotaryKilnAsset.js'

function StaticChartHost({ className, ariaLabel }) {
  return h('div', { className: `chart ${className}`, role: 'img', 'aria-label': ariaLabel })
}

function StaticModelHost({ className = '', modelUrl, ariaLabel }) {
  return h('div', { className, 'data-model-url': modelUrl, role: 'img', 'aria-label': ariaLabel })
}

function Panel({ title, meta, className = '', children }) {
  return h('section', { className: `rk-panel ${className}` },
    h('header', { className: 'rk-panel__header' },
      h('h2', null, h('i', { 'aria-hidden': true }), title),
      meta && h('span', null, meta),
    ),
    h('div', { className: 'rk-panel__body' }, children),
  )
}

function TrendLegend({ items }) {
  return h('div', { className: 'rk-legend', 'aria-hidden': true },
    ...items.map((item) => h('span', { key: item.name },
      h('i', { style: { background: item.color } }), item.name,
    )),
  )
}

export function RotaryKilnDashboard({
  data = rotaryKilnData,
  ChartComponent = StaticChartHost,
  ModelComponent = StaticModelHost,
  temperatureOption,
  energyOption,
}) {
  return h('main', { className: 'rotary-kiln-dashboard' },
    h('div', { className: 'rk-grid-glow', 'aria-hidden': true }),
    h('header', { className: 'rk-topbar' },
      h('div', { className: 'rk-brand' },
        h('span', { className: 'rk-brand__mark', 'aria-hidden': true }, 'RK'),
        h('div', null,
          h('p', null, 'PROCESS EQUIPMENT DIGITAL TWIN'),
          h('strong', null, '大塚综合数字孪生平台'),
        ),
      ),
      h('div', { className: 'rk-title' },
        h('span', null, 'ROTARY KILN MONITORING'),
        h('h1', null, '回转窑运行监测'),
      ),
      h('div', { className: 'rk-device' },
        h('div', null, h('span', null, `${data.device.line} · ${data.device.code}`), h('strong', null, data.device.status)),
        h('i', { 'aria-hidden': true }),
        h('time', null, data.device.updatedAt),
      ),
    ),

    h('section', { className: 'rk-kpis', 'aria-label': '回转窑核心运行指标' },
      ...data.kpis.map((metric) => h('article', { className: `rk-kpi rk-kpi--${metric.tone}`, key: metric.label },
        h('span', { className: 'rk-kpi__icon', 'aria-hidden': true }, metric.icon),
        h('div', { className: 'rk-kpi__metric' }, h('span', null, metric.label), h('strong', null, metric.value, h('small', null, metric.unit))),
        h('div', { className: 'rk-kpi__delta' }, h('span', null, '较班前'), h('strong', null, metric.delta)),
      )),
    ),

    h('div', { className: 'rk-content' },
      h('div', { className: 'rk-column rk-column--left' },
        h(Panel, { title: '温度场监测', meta: '5 区在线 · 无超限', className: 'rk-temperature-panel' },
          h('div', { className: 'rk-zones' },
            ...data.temperatureZones.map((zone) => h('article', { className: `rk-zone rk-zone--${zone.tone}`, key: zone.label },
              h('div', { className: 'rk-zone__label' }, h('span', null, zone.label), h('small', null, zone.range)),
              h('strong', null, zone.value, h('em', null, '℃')),
              h('div', { className: 'rk-zone__track', 'aria-hidden': true }, h('i', { style: { width: `${zone.percent}%` } })),
              h('span', { className: 'rk-zone__state' }, '● 稳定'),
            )),
          ),
        ),
        h(Panel, { title: '燃烧与供风', meta: '空燃比 9.8 : 1', className: 'rk-combustion-panel' },
          h('div', { className: 'rk-flame-summary' },
            h('div', { className: 'rk-flame', 'aria-hidden': true }, h('i'), h('i'), h('i')),
            h('div', null, h('span', null, '火焰核心温度'), h('strong', null, '1,468', h('small', null, '℃'))),
            h('dl', null, h('div', null, h('dt', null, '燃烧器开度'), h('dd', null, '68%')), h('div', null, h('dt', null, '火焰稳定度'), h('dd', null, '96.4%'))),
          ),
          h('div', { className: 'rk-flow-list' },
            ...data.combustion.map((row) => h('div', { key: row.label },
              h('span', null, row.label),
              h('div', { className: 'rk-flow-list__bar' }, h('i', { style: { width: `${row.percent}%` } })),
              h('strong', null, row.value, h('small', null, row.unit)),
            )),
          ),
        ),
      ),

      h('div', { className: 'rk-column rk-column--center' },
        h(Panel, { title: '窑体工艺状态', meta: `${data.device.uptime} · 自动控制`, className: 'rk-process-panel' },
          h('div', { className: 'rk-process-meta' },
            h('span', null, '工单号', h('strong', null, 'SC260907-03')),
            h('span', null, '产品', h('strong', null, 'POTICON')),
            h('span', null, '目标产量', h('strong', null, '19.0 t/h')),
            h('span', null, '控制模式', h('strong', null, 'DCS 自动')),
          ),
          h('div', { className: 'rk-kiln-scene', 'aria-label': '回转窑五段工艺状态示意图' },
            h(ModelComponent, { className: 'rk-kiln-model', modelUrl: ROTARY_KILN_MODEL_URL, ariaLabel: '回转窑三维设备模型' }),
            h('div', { className: 'rk-process-flow' },
              ...data.process.map((node, index) => h('article', { key: node.label, className: index === 3 ? 'is-active' : '' },
                h('span', null, String(index + 1).padStart(2, '0')),
                h('div', null, h('strong', null, node.label), h('small', null, node.value)),
              )),
            ),
          ),
        ),
        h(Panel, { title: '24 小时温度与压力趋势', meta: '采样周期 1 min', className: 'rk-temperature-trend' },
          h(TrendLegend, { items: data.temperatureTrend.series }),
          h(ChartComponent, { option: temperatureOption, className: 'rk-chart rk-chart--temperature', ariaLabel: '回转窑温度与压力趋势' }),
        ),
      ),

      h('div', { className: 'rk-column rk-column--right' },
        h(Panel, { title: '设备健康度', meta: '综合健康 90.4%', className: 'rk-health-panel' },
          h('div', { className: 'rk-health-score' },
            h('div', { className: 'rk-health-ring' }, h('strong', null, '90'), h('span', null, '健康指数')),
            h('dl', null, h('div', null, h('dt', null, '设备状态'), h('dd', null, '优')), h('div', null, h('dt', null, '预测风险'), h('dd', null, '低'))),
          ),
          h('div', { className: 'rk-health-list' },
            ...data.health.map((item) => h('div', { key: item.label },
              h('span', null, item.label, h('small', null, item.note)),
              h('i', { 'aria-hidden': true }, h('b', { style: { width: `${item.level}%` } })),
              h('strong', null, item.value),
            )),
          ),
        ),
        h(Panel, { title: '能耗趋势', meta: '电耗 / 燃气', className: 'rk-energy-panel' },
          h(ChartComponent, { option: energyOption, className: 'rk-chart rk-chart--energy', ariaLabel: '回转窑能耗趋势' }),
        ),
        h(Panel, { title: '告警与运维', meta: '1 条关注', className: 'rk-alarm-panel' },
          h('div', { className: 'rk-alarm-list' },
            ...data.alarms.map((alarm) => h('article', { className: `rk-alarm rk-alarm--${alarm.level}`, key: `${alarm.time}-${alarm.title}` },
              h('time', null, alarm.time), h('i', { 'aria-hidden': true }, '!'), h('div', null, h('strong', null, alarm.title), h('span', null, alarm.detail)),
            )),
          ),
          h('div', { className: 'rk-maintenance' },
            h('div', null, h('span', null, '下次保养'), h('strong', null, data.maintenance.next), h('small', null, data.maintenance.task)),
            h('div', { className: 'rk-maintenance__track' }, h('i', { style: { width: `${data.maintenance.progress}%` } })),
            h('span', null, `累计 ${data.maintenance.runtime} · ${data.maintenance.owner}`),
          ),
        ),
      ),
    ),

    h('footer', { className: 'rk-footer' },
      h('div', null, h('span', null, '网络'), h('strong', null, 'DCS 通讯正常')),
      ...data.material.map((item) => h('div', { key: item.label }, h('span', null, item.label), h('strong', null, item.value), h('em', null, item.state))),
      h('div', null, h('span', null, '数据质量'), h('strong', null, '99.98%'), h('em', null, '可信')),
    ),
  )
}
