export const factoryCampusRegistry = [
  {
    id: 'main-production-hall',
    name: '主生产车间',
    type: '大型生产厂房',
    status: '正常',
    metricLabel: '当前负荷',
    metricValue: '78%',
    temperature: '26°C',
    position: [-7.3, 0, 1.7],
    size: [11.6, 3.0, 5.6],
    levels: 1,
    roofType: 'shallow',
    accent: 'blue',
  },
  {
    id: 'central-processing-hall',
    name: '中央处理车间',
    type: '连续生产厂房',
    status: '正常',
    metricLabel: '处理能力',
    metricValue: '86 t/h',
    temperature: '29°C',
    position: [-0.8, 0, -2.7],
    size: [9.6, 3.1, 4.3],
    levels: 2,
    roofType: 'shallow',
    accent: 'cyan',
  },
  {
    id: 'rear-high-bay',
    name: '后区高跨车间',
    type: '高跨生产厂房',
    status: '正常',
    metricLabel: '设备稼动率',
    metricValue: '91%',
    temperature: '27°C',
    position: [-0.2, 0, -7.3],
    size: [8.2, 4.2, 4.1],
    levels: 2,
    roofType: 'shallow',
    accent: 'blue',
  },
  {
    id: 'west-service-hall',
    name: '西区辅助车间',
    type: '生产辅助设施',
    status: '正常',
    metricLabel: '当前负荷',
    metricValue: '62%',
    temperature: '25°C',
    position: [-9.8, 0, -5.3],
    size: [5.4, 2.4, 3.6],
    levels: 1,
    roofType: 'flat',
    accent: 'neutral',
  },
  {
    id: 'east-process-hall',
    name: '东区工艺车间',
    type: '工艺生产厂房',
    status: '正常',
    metricLabel: '生产效率',
    metricValue: '84%',
    temperature: '28°C',
    position: [6.8, 0, -5.7],
    size: [6.0, 2.7, 3.8],
    levels: 1,
    roofType: 'flat',
    accent: 'blue',
  },
  {
    id: 'right-warehouse',
    name: '东区成品仓库',
    type: '仓储设施',
    status: '正常',
    metricLabel: '仓储占用率',
    metricValue: '73%',
    temperature: '23°C',
    position: [7.0, 0, 0.5],
    size: [7.5, 2.6, 4.5],
    levels: 1,
    roofType: 'shallow',
    accent: 'cyan',
  },
  {
    id: 'right-utility',
    name: '东区动力站',
    type: '公用工程设施',
    status: '正常',
    metricLabel: '能源负荷',
    metricValue: '68%',
    temperature: '31°C',
    position: [11.3, 0, -4.5],
    size: [4.2, 2.3, 3.1],
    levels: 2,
    roofType: 'stepped',
    accent: 'cyan',
  },
  {
    id: 'front-warehouse',
    name: '前区原料仓库',
    type: '仓储设施',
    status: '正常',
    metricLabel: '仓储占用率',
    metricValue: '66%',
    temperature: '22°C',
    position: [3.0, 0, 5.8],
    size: [7.4, 2.7, 3.7],
    levels: 1,
    roofType: 'shallow',
    accent: 'blue',
  },
  {
    id: 'laboratory',
    name: '质量检测中心',
    type: '检验研发设施',
    status: '正常',
    metricLabel: '设备在线率',
    metricValue: '96%',
    temperature: '24°C',
    position: [10.6, 0, 4.8],
    size: [4.5, 2.4, 3.0],
    levels: 2,
    roofType: 'flat',
    accent: 'neutral',
  },
  {
    id: 'administration',
    name: '园区管理中心',
    type: '综合办公楼',
    status: '正常',
    metricLabel: '当前用电',
    metricValue: '12.8 MW',
    temperature: '24°C',
    position: [-5.5, 0, 8.2],
    size: [5.2, 3.9, 3.2],
    levels: 4,
    roofType: 'flat',
    accent: 'cyan',
  },
]

export const factoryCampusById = new Map(
  factoryCampusRegistry.map((record) => [record.id, record]),
)
